name: watch

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  azure_docs:
    name: azure-docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Calculate diff
      run: |
        curl https://raw.githubusercontent.com/MicrosoftDocs/azure-docs/main/articles/virtual-machines/sizes.md --output .github/snapshots/size.md
    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        title: 🤖 MicrosoftDocs/azure-docs changes
        commit-message: |
          Manually edit https://github.com/terraform-linters/tflint-ruleset-azurerm/edit/create-pull-request/patch/rules/utils.go
          based on https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/virtual-machines/sizes.md
        delete-branch: true
